### ISSUE TITLE
Update to Alamofire 3.0

### ISSUE THREAD

**Issue by iasandcb** [luckymarmot/Paw-SwiftAlamofireCodeGenerator#2]
The current generator emits code based on 1.0.

**Comment by mittsh** [comment]
Yeah, it's something we want to do for a long time!

**Comment by iasandcb** [comment]
manager.request(.GET, "https://api.parse.com/1/classes/CartItem")
            .validate(statusCode: 200..<300)
            .responseJSON{ response in
                guard response.result.error == nil else {
                    // error
                    return
                }
                if let JSON = response.result.value {
                    print("JSON: \(JSON)")
                }
        }

is recommended

**Comment by iasandcb** [comment]
let manager = Manager.sharedInstance
        
        // Add Headers
        manager.session.configuration.HTTPAdditionalHeaders = [
            "X-Parse-REST-API-Key":"d0zRCiGFS2Becr3fVDlV9UDwnnCjLofWlIyPBbEq",
            "X-Parse-Application-Id":"Jrfrtb7blTPVKEPKS2OC0QgE0RTKqQzZHNxKrfoR",
        ]
doesn't work.

        var defaultHeaders = Alamofire.Manager.sharedInstance.session.configuration.HTTPAdditionalHeaders ?? [:]
        defaultHeaders["X-Parse-REST-API-Key"] = "d0zRCiGFS2Becr3fVDlV9UDwnnCjLofWlIyPBbEq"
        defaultHeaders["X-Parse-Application-Id"] = "Jrfrtb7blTPVKEPKS2OC0QgE0RTKqQzZHNxKrfoR"
        
        let configuration = NSURLSessionConfiguration.defaultSessionConfiguration()
                configuration.HTTPAdditionalHeaders = defaultHeaders
        
        let manager = Alamofire.Manager(configuration: configuration)

does work.

**Comment by mittsh** [comment]
It's now fixed in 1.1.0: updated to Swift 2 and Alamofire 3 :)
