### ISSUE TITLE
URLParameters is missing

### ISSUE THREAD

**Issue by iasandcb** [luckymarmot/Paw-SwiftAlamofireCodeGenerator#4]
in spite of no URL params, the generated code is

Alamofire.request(.GET, "https://api.parse.com/1/classes/CartItem", parameters: URLParameters) 

where variable URLParameters is not defined.

**Comment by mittsh** [comment]
Sorry for the late answer @iasandcb
We have fixed this in the new version 1.1.0 which also updates to Swift 2 and Alamofire 3
