### ISSUE TITLE
Update to Alamofire 4 for Swift 3

### ISSUE THREAD

**Issue by NinoScript** [luckymarmot/Paw-SwiftAlamofireCodeGenerator#8]
The current generator emits code based on Alamofire 3 for Swift 2.
( Related to this closed issue: #2 )

**Comment by mittsh** [comment]
It's true! Something we should update and it shouldn't be too hard 😀Thanks for the suggestion!

**Comment by MoathOthman** [comment]
Any Update on this ?! thank you

**Comment by mittsh** [comment]
Sadly I had no time to work on this, but will push it up on our list.

**Comment by MoathOthman** [comment]
That would be great

**Comment by andypye** [comment]
This would definitely be handy, as this feature is really nice to get a quick draft of the code required

**Comment by mittsh** [comment]
It's all done! Paw should automatically update if it's not the case you can trigger a manual update in the Paw menu > Extensions > Check for Extensions Updates…

It's now Swift 3 + Alamofire 4 😉 

cc @nfgrilo

**Comment by MoathOthman** [comment]
Great job guys, many thnx 👍 . Just used it and its working perfectly.
